# Generated by Django 6.0.6 on 2026-06-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='vendido',
            field=models.BooleanField(default=False, verbose_name='Vendido'),
        ),
    ]
