services:
  web:
    build: .
    container_name: panos_web
    restart: unless-stopped
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DJANGO_SUPERUSER_EMAIL: admin@gmail.com
      DJANGO_SUPERUSER_PASSWORD: admin123
