"""
Django settings for panoslar project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from panoslar.storage import MinIOMediaStorage  # noqa: E402 – imported after env is ready

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY', 'django-insecure-m0*p&ro8#l3v^f6d-elyb=g2#qwq6j^o81v735)!xt(ygdz6r1'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]

CSRF_TRUSTED_ORIGINS = [
    f'https://{h}' for h in ALLOWED_HOSTS if h not in ('localhost', '127.0.0.1')
]

# Diretório para dados persistentes (banco de dados e mídia).
# Em produção (Railway), aponte DATA_DIR para o caminho do volume montado.
DATA_DIR = Path(os.getenv('DATA_DIR', BASE_DIR))


# Application definition

INSTALLED_APPS = [
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'loja',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'panoslar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'loja.context_processors.configuracoes_loja',
            ],
        },
    },
]

WSGI_APPLICATION = 'panoslar.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.getenv('DB_NAME', os.getenv('MYSQLDATABASE', 'panoslar')),
        'USER': os.getenv('DB_USER', os.getenv('MYSQLUSER', 'root')),
        'PASSWORD': os.getenv('DB_PASSWORD', os.getenv('MYSQLPASSWORD', '')),
        'HOST': os.getenv('DB_HOST', os.getenv('MYSQLHOST', 'db')),
        'PORT': os.getenv('DB_PORT', os.getenv('MYSQLPORT', '3306')),
        'OPTIONS': {'charset': 'utf8mb4'},
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Usa o MinIO apenas quando configurado (ex: produção no Railway).
# Sem MINIO_ENDPOINT, os uploads continuam indo para MEDIA_ROOT (disco local).
if os.getenv('MINIO_ENDPOINT'):
    STORAGES['default'] = {
        'BACKEND': 'panoslar.storage.MinIOMediaStorage',
    }

# ---------------------------------------------------------------------------
# MinIO / S3-compatible object storage
# ---------------------------------------------------------------------------
# boto3 / django-storages read these standard AWS_* names automatically.
# NOTE: AWS_S3_ENDPOINT_URL is intentionally NOT set here.  Setting it
# globally would cause boto3 to generate image URLs pointing at the private
# internal endpoint (MINIO_ENDPOINT), which browsers cannot reach.  Instead,
# MinIOMediaStorage sets endpoint_url to the private endpoint only for the
# upload connection, and uses custom_domain for public URL generation.
AWS_ACCESS_KEY_ID = os.getenv('MINIO_ACCESS_KEY', '')
AWS_SECRET_ACCESS_KEY = os.getenv('MINIO_SECRET_KEY', '')
AWS_STORAGE_BUCKET_NAME = os.getenv('MINIO_BUCKET_NAME', 'media')
AWS_S3_REGION_NAME = 'us-east-1'          # MinIO default region
AWS_S3_SIGNATURE_VERSION = 's3v4'         # required by MinIO
AWS_S3_USE_SSL = False                     # plain HTTP on the private network
AWS_S3_ADDRESSING_STYLE = 'path'          # path-style URLs (MinIO requirement)
AWS_QUERYSTRING_AUTH = False              # serve files without signed URLs
AWS_S3_FILE_OVERWRITE = True              # overwrite on re-upload keeps URLs stable

# Media files (uploads do usuário)
# MEDIA_URL points to the public MinIO endpoint so that image URLs generated
# by img.url are reachable by browsers.  The storage backend continues to use
# MINIO_ENDPOINT (private) for uploads — fast internal communication.
# MEDIA_ROOT is kept for local fallback / management commands.
_minio_public_endpoint = os.getenv('MINIO_PUBLIC_ENDPOINT', '').rstrip('/')
_minio_bucket = os.getenv('MINIO_BUCKET_NAME', 'media')
MEDIA_URL = f'{_minio_public_endpoint}/{_minio_bucket}/' if _minio_public_endpoint else 'media/'
MEDIA_ROOT = DATA_DIR / 'media'

# Configurações da loja
WHATSAPP_NUMERO = os.getenv('WHATSAPP_NUMERO')  # DDI+DDD+numero
NOME_LOJA = os.getenv('NOME_LOJA')
INSTAGRAM_URL = os.getenv('INSTAGRAM_URL', '')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Painel administrativo (autenticação)
LOGIN_URL = 'painel:login'
LOGIN_REDIRECT_URL = 'painel:produto_lista'
LOGOUT_REDIRECT_URL = 'painel:login'